name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install --yes mono-devel

      - name: Build application
        run: xbuild SimpleX.csproj /target:Rebuild /property:Configuration=Debug /property:Platform=x86
